joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  # Hz

joint01_left_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint01_left

joint01_right_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint01_right

joint04_left_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint04_left

joint04_right_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint04_right

joint_tire_left_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_tire_left

joint_tire_right_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint_tire_right