controller_joint_names: ['', 'joint01_left', 'joint12_left', 'joint23_left', 'joint_tire_left', 'joint04_left', 'joint43_left', 'joint01_right', 'joint12_right', 'joint23_right', 'joint_tire_right', 'joint04_right', 'joint43_right', ]
