# 平衡机器人控制器配置
# 添加joint_state_controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  # Hz
  
# 平衡机器人控制器配置
balance_robot_controller:
  type: balance_robot_controller/BalanceRobotController
  publish_rate: 50
  # 其他配置保持不变
  
  # 控制的关节列表
  joints:
    - joint01_left     # 左前腿关节
    - joint01_right    # 右前腿关节
    - joint04_left     # 左后腿关节
    - joint04_right    # 右后腿关节
    - joint_tire_left  # 左轮
    - joint_tire_right # 右轮
    
  # 控制器参数
  gains:
    # Yaw 控制器（航向）– you probably don’t need 100 Nm/rad of yaw
    yaw_p:        5.0
    yaw_d:        1.0
    yaw_max_out:  1.0

    # Roll 控制器（侧倾）– gentler P, a bit more D
    roll_p:       40.0    # ↓ from 100
    roll_d:       50.0    # ↑ from 20
    roll_max_out: 3.0     # ↓ from 8

    # 腿部长度控制器 – must exceed static weight (~6 N)
    leg_length_p:       80.0   # ↑ from 100, to stiffen under load
    leg_length_d:       20.0    # ↑ from 8, to damp leg bounce
    leg_length_max_out: 8.0    # ↑ from 0.5, give ≈2× static load

    # 腿部角度控制器 – use a real P
    leg_angle_p:        30.0    # ↑ from 5
    leg_angle_d:         10.0    # small damping
    leg_angle_max_out:   5.0    # clamp torque to ±10 Nm

  target:
    leg_length: 0.07
    roll_angle: 0.0

  physics:
    wheel_radius: 0.026
    leg_mass:     0.05